// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace EndToEndDB.Data.EndToEnd
{
    public partial class BookData
    {
        public int BookId { get; set; }
        public string BookTitle { get; set; }
        public string BookDescription { get; set; }
        public int? BookPrice { get; set; }
        public string BookAuthor { get; set; }
    }
}