// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace EndToEndDB.Data.EndToEnd
{
    public partial class EndtoEndContext : DbContext
    {
        public EndtoEndContext()
        {
        }

        public EndtoEndContext(DbContextOptions<EndtoEndContext> options)
            : base(options)
        {
        }

        public virtual DbSet<BookData> BookData { get; set; }
        public virtual DbSet<WeatherForecast> WeatherForecast { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<BookData>(entity =>
            {
                entity.HasKey(e => e.BookId)
                    .HasName("PK__BookData__3DE0C2076FDAE340");

                entity.Property(e => e.BookAuthor).HasMaxLength(50);

                entity.Property(e => e.BookDescription).HasMaxLength(50);

                entity.Property(e => e.BookTitle).HasMaxLength(50);

                entity.Property(e => e.UserName).HasMaxLength(50);
            });

            modelBuilder.Entity<WeatherForecast>(entity =>
            {
                entity.Property(e => e.Date).HasColumnType("datetime");

                entity.Property(e => e.Summary).HasMaxLength(50);

                entity.Property(e => e.UserName).HasMaxLength(50);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}